- name: "Download Wordpress"
  get_url:
    url: "https://br.wordpress.org/wordpress-5.0.11-pt_BR.tar.gz"
    dest: "/tmp/wordpress.tar.gz"

- name: "Unzip Wordpress"
  unarchive:
    src: "/tmp/wordpress.tar.gz"
    dest: "/var/www/"
    remote_src: yes
  become: yes

- name: "Create Wordpress config"
  copy:
    src: "/var/www/wordpress/wp-config-sample.php"
    dest: "/var/www/wordpress/wp-config.php"
    remote_src: yes
  become: yes
    
- name: "Configure Wordpress db"
  replace: 
    path: "/var/www/wordpress/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
    - { regex: 'nome_do_banco_de_dados_aqui', value: "{{ wp_db_name }}"}
    - { regex: 'nome_de_usuario_aqui', value: "{{ wp_user_name }}"}
    - { regex: 'senha_aqui', value: "{{ wp_user_pass }}"}
    - { regex: 'localhost', value: "{{ mysql_host }}"}
  become: yes

- name: "Configure apache to serve wordpress"
  template:
    src: "templates/000-default.conf"
    dest: "/etc/apache2/sites-available/000-default.conf"
  become: yes
  notify: restart_apache
